apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: customgp2  # Use your custom StorageClass
  hostPath:
    path: "/mnt/data"  # For local storage (Change this for cloud environments)
