apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
