apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z postgres 5432; do sleep 2; done']
        - name: copy-config
          image: busybox
          command: ["/bin/sh", "-c", "cp -r /config/* /vault/config/ || true"]
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: config-source
              mountPath: /config
      containers:
        - name: vault
          image: hashicorp/vault:latest
          imagePullPolicy: IfNotPresent
          args: ["server"]
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
          ports:
            - containerPort: 8200
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
      volumes:
        - name: config-source
          configMap:
            name: vault-config
        - name: vault-config
          emptyDir: {}
