apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      initContainers:
        - name: wait-for-postgres
          image: alpine
          command: ["sh", "-c", "until nc -z postgres 5432; do sleep 2; done"]
          # Alpine has netcat pre-installed

        - name: copy-config
          image: busybox
          command: ["/bin/sh", "-c", "cp -r /config/* /vault/config/"]
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: config-source
              mountPath: /config
          securityContext:
            runAsUser: 0  # Allows writing to /vault/config/

      containers:
        - name: vault
          image: hashicorp/vault:latest
          imagePullPolicy: IfNotPresent
          command: ["vault", "server"]
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]  # Moved to the correct location

      volumes:
        - name: config-source
          configMap:
            name: vault-config
        - name: vault-config
          emptyDir: {}  # Allows writes

