apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ["sh", "-c", "until nc -z postgres.default.svc.cluster.local 5432; do sleep 2; done"]
      containers:
        - name: vault
          image: "{{ .Values.vault.image }}"  # Ensure this value is correctly defined in values.yaml
          imagePullPolicy: IfNotPresent
          args: ["server", "-dev"]
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root"
          ports:
            - containerPort: 8200
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
